// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkbelhbawlsayfjsopta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrYmVsaGJhd2xzYXlmanNvcHRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Nzg1MDgsImV4cCI6MjA3MTI1NDUwOH0.AcUWa1NFnZXNW3vP4eh3P8kEfW90RvHzW6KrX_wVuQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});